In [1]:
import tensorflow.compat.v1 as tf
import numpy as np
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
# Evaluation our model using this test dataset
# traning Data Set을 먼저 학습하고 Test set을 학습한 Model에 넣는다
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        #Traning
        cost_val,W_val,_ = sess.run([cost,W,optimizer],
                                   feed_dict={X:x_data, Y:y_data})
        print(step,cost_val,W_val)
    
    #Test
    print("Prediction :",sess.run(prediction,feed_dict={X:x_test}))
    #calc Accuracy
    print("Accuracy:",sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))
    

0 4.7119417 [[ 3.419112   -0.13291475  0.4929202 ]
 [-0.89855665  0.907253   -0.6178503 ]
 [ 1.502978    0.6169577   0.15833265]]
1 3.905056 [[ 3.398296   -0.14953633  0.53035754]
 [-0.8690134   0.77784944 -0.51798993]
 [ 1.5007068   0.53181005  0.24575154]]
2 3.513998 [[ 3.3637288  -0.15236323  0.5677518 ]
 [-0.9098542   0.7189358  -0.4182356 ]
 [ 1.4307066   0.51445967  0.33310217]]
3 3.186748 [[ 3.3322594  -0.15818323  0.60504127]
 [-0.93447554  0.64407694 -0.31875536]
 [ 1.3764106   0.48159793  0.42025992]]
4 2.8627007 [[ 3.2996438  -0.16263422  0.6421079 ]
 [-0.9659347   0.5767307  -0.21994999]
 [ 1.3156126   0.45576715  0.5068888 ]]
5 2.544664 [[ 3.2679923  -0.16746458  0.6785897 ]
 [-0.9933355   0.50749147 -0.12330992]
 [ 1.258784    0.42783615  0.5916482 ]]
6 2.2461648 [[ 3.2370696  -0.17118308  0.7132308 ]
 [-1.0186901   0.4447351  -0.03519897]
 [ 1.2040435   0.40560853  0.6686164 ]]
7 2.017641 [[ 3.208983   -0.17183112  0.7419654 ]
 [-1.0315819   0.40124133  0.02118653]
 [ 1.

81 0.914516 [[ 2.019085   -0.03973647  1.7997676 ]
 [-0.2330675  -0.27984753 -0.09623897]
 [ 0.8370781   1.0558283   0.38536236]]
82 0.9098266 [[ 2.0084417  -0.03925134  1.8099257 ]
 [-0.22954524 -0.28150308 -0.09810568]
 [ 0.8379099   1.0574884   0.38287047]]
83 0.9052334 [[ 1.9979025  -0.03878003  1.8199936 ]
 [-0.22611217 -0.2830683  -0.09997353]
 [ 0.8387849   1.0590665   0.38041732]]
84 0.900733 [[ 1.9874654  -0.0383218   1.8299725 ]
 [-0.2227653  -0.28454664 -0.10184205]
 [ 0.8397009   1.060566    0.378002  ]]
85 0.8963227 [[ 1.9771285  -0.037876    1.8398635 ]
 [-0.21950167 -0.28594154 -0.1037108 ]
 [ 0.8406558   1.0619895   0.3756235 ]]
86 0.8919997 [[ 1.9668901  -0.03744195  1.8496679 ]
 [-0.2163184  -0.28725627 -0.10557935]
 [ 0.84164774  1.0633403   0.37328088]]
87 0.8877613 [[ 1.9567485  -0.03701903  1.8593867 ]
 [-0.2132128  -0.28849396 -0.10744725]
 [ 0.8426748   1.064621    0.3709732 ]]
88 0.8836049 [[ 1.9467018  -0.03660662  1.8690209 ]
 [-0.21018225 -0.28965768 -0.1093

In [3]:
#Learning Rate = 1.5 ( overShooting )

X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        #Traning
        cost_val,W_val,_ = sess.run([cost,W,optimizer],
                                   feed_dict={X:x_data, Y:y_data})
        print(step,cost_val,W_val)
    
    #Test
    print("Prediction :",sess.run(prediction,feed_dict={X:x_test}))
    #calc Accuracy
    print("Accuracy:",sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))
    

0 3.0281308 [[ 1.7348107   1.2917418  -1.8066033 ]
 [ 2.1753414   2.6340127  -3.2620056 ]
 [ 0.9761262   0.74997294 -5.587759  ]]
1 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
2 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
3 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
15 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
16 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
17 nan [[nan nan nan]
 [nan nan

184 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
185 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
186 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
187 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
188 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
189 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
190 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
191 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
192 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
193 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
194 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
195 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
196 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
197 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
198 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
199 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
200 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Prediction : [0 0 0]
Accuracy: 0.0


In [4]:
#Learning Rate = very Small Learning Rate

X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        #Traning
        cost_val,W_val,_ = sess.run([cost,W,optimizer],
                                   feed_dict={X:x_data, Y:y_data})
        print(step,cost_val,W_val)
    
    #Test
    print("Prediction :",sess.run(prediction,feed_dict={X:x_test}))
    #calc Accuracy
    print("Accuracy:",sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))

    
#Local Minimum에 빠져버리게됨

0 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
1 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
2 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
3 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
4 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
5 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
6 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
7 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]


89 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
90 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
91 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
92 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
93 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
94 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
95 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
96 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23

189 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
190 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
191 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
192 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
193 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
194 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
195 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.73891807  0.23120531]
 [ 1.1218731   0.45710415 -2.0219498 ]]
196 10.950874 [[ 0.7438008  -0.45698187  0.25909874]
 [ 2.8620439   0.738918

In [7]:
from sklearn.preprocessing import MinMaxScaler

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
#Normalized inputs
xy = MinMaxScaler().fit_transform(xy) 

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2.4014752 
Prediction:
 [[1.8491496]
 [2.3205857]
 [2.105643 ]
 [1.8764119]
 [1.9692953]
 [1.9963529]
 [1.9157419]
 [2.1214194]]
1 Cost:  2.401322 
Prediction:
 [[1.8490821]
 [2.3205168]
 [2.105585 ]
 [1.8763664]
 [1.9692421]
 [1.9963013]
 [1.9157047]
 [2.1213818]]
2 Cost:  2.4011686 
Prediction:
 [[1.8490145]
 [2.320448 ]
 [2.105527 ]
 [1.8763207]
 [1.969189 ]
 [1.9962497]
 [1.9156675]
 [2.121344 ]]
3 Cost:  2.4010155 
Prediction:
 [[1.848947 ]
 [2.3203788]
 [2.105469 ]
 [1.8762752]
 [1.9691359]
 [1.996198 ]
 [1.9156303]
 [2.1213064]]
4 Cost:  2.4008622 
Prediction:
 [[1.8488796]
 [2.3203099]
 [2.105411 ]
 [1.8762295]
 [1.9690828]
 [1.9961464]
 [1.9155931]
 [2.1212687]]
5 Cost:  2.4007092 
Prediction:
 [[1.848812 ]
 [2.320241 ]
 [2.105353 ]
 [1.876184 ]
 [1.9690297]
 [1.9960948]
 [1.9155558]
 [2.121231 ]]
6 Cost:  2.4005558 
Prediction:
 [[1.8487445]
 [2.3201718]
 [2.1052952]
 [1.8761383]
 [1.9689765]
 [1.9960432]
 [1.9155186]
 [2.1211934]]
7 Cost:  2.4004025 
Prediction:
 [[

 [[1.8435531]
 [2.3148682]
 [2.1008363]
 [1.8726319]
 [1.9648914]
 [1.9920744]
 [1.9126564]
 [2.118295 ]]
84 Cost:  2.3886404 
Prediction:
 [[1.8434857]
 [2.3147993]
 [2.1007786]
 [1.8725865]
 [1.9648385]
 [1.992023 ]
 [1.9126194]
 [2.1182575]]
85 Cost:  2.3884883 
Prediction:
 [[1.8434185]
 [2.3147306]
 [2.100721 ]
 [1.8725411]
 [1.9647856]
 [1.9919715]
 [1.9125823]
 [2.1182199]]
86 Cost:  2.3883362 
Prediction:
 [[1.8433512]
 [2.314662 ]
 [2.100663 ]
 [1.8724957]
 [1.9647326]
 [1.9919201]
 [1.9125452]
 [2.1181824]]
87 Cost:  2.388184 
Prediction:
 [[1.8432839]
 [2.3145933]
 [2.1006052]
 [1.8724501]
 [1.9646797]
 [1.9918687]
 [1.9125081]
 [2.1181448]]
88 Cost:  2.388032 
Prediction:
 [[1.8432167]
 [2.3145244]
 [2.1005476]
 [1.8724047]
 [1.9646268]
 [1.9918172]
 [1.912471 ]
 [2.1181073]]
89 Cost:  2.3878796 
Prediction:
 [[1.8431494]
 [2.3144557]
 [2.1004896]
 [1.8723593]
 [1.9645737]
 [1.9917659]
 [1.912434 ]
 [2.1180696]]
90 Cost:  2.3877277 
Prediction:
 [[1.8430821]
 [2.314387 ]
 [